import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Menu() {
  return (
    <nav style={{
      width: "100%",
      background: "black",
      borderBottom: "1px solid #eee",
      padding: "0 32px",
      position: "sticky",
      top: 0,
      zIndex: 100,
      fontWeight: 500
    }}>
      <div style={{
        maxWidth: 1200,
        margin: "0 auto",
        display: "flex",
        alignItems: "center",
        height: 64,
        gap: 32
      }}>
        <Link href="/" style={{ fontWeight: 800, fontSize: 24, color: "#2575fc", textDecoration: "none", marginRight: 32 }}>
          Thrivex Studio
        </Link>
        <Link href="/" style={{ marginRight: 24 }}>Home</Link>
        <div style={{ position: "relative", marginRight: 24 }}>
          <span>Services ▾</span>
          <div style={{
            display: "none", // Will show on hover with JS later
            position: "absolute",
            top: 32,
            left: 0,
            background: "#fff",
            border: "1px solid #eee",
            borderRadius: 8,
            boxShadow: "0 2px 12px rgba(0,0,0,0.06)",
            minWidth: 220,
            zIndex: 10
          }}>
            <div style={{ padding: 12, borderBottom: "1px solid #f0f0f0" }}>
              <b>Podfast</b>
              <div style={{ fontSize: 14, color: "#666" }}>Fast podcast editing</div>
              <div style={{ fontSize: 14, color: "#666" }}>Podcast setup & strategy</div>
              <div style={{ fontSize: 14, color: "#666" }}>Hosting & distribution</div>
            </div>
            <div style={{ padding: 12, borderBottom: "1px solid #f0f0f0" }}>
              <b>Web Development</b>
              <div style={{ fontSize: 14, color: "#666" }}>Website design</div>
              <div style={{ fontSize: 14, color: "#666" }}>Front-end/back-end dev</div>
              <div style={{ fontSize: 14, color: "#666" }}>E-commerce solutions</div>
            </div>
            <div style={{ padding: 12 }}>
              <b>Video Recording</b>
              <div style={{ fontSize: 14, color: "#666" }}>Studio rental</div>
              <div style={{ fontSize: 14, color: "#666" }}>On-site recording</div>
              <div style={{ fontSize: 14, color: "#666" }}>Editing & post-production</div>
            </div>
          </div>
        </div>
        <Link href="/portfolio" style={{ marginRight: 24 }}>Portfolio / Work</Link>
        <Link href="/about-us" style={{ marginRight: 24 }}>About Us</Link>
        <Link href="/blog" style={{ marginRight: 24 }}>Blog / Resources</Link>
        <Link href="/pricing" style={{ marginRight: 24 }}>Pricing / Packages</Link>
        <Link href="/contact" style={{ marginRight: 24 }}>Contact</Link>
        <div style={{ flex: 1 }} />
        <a href="#cta" style={{
          background: "#2575fc",
          color: "#fff",
          padding: "10px 28px",
          borderRadius: 24,
          fontWeight: 700,
          fontSize: 16,
          textDecoration: "none"
        }}>
          Start Your Project
        </a>
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Menu />
        {children}
      </body>
    </html>
  );
}
