import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import styles from "./menu.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Menu() {
  return (
    <nav style={{
      width: "100%",
      background: "black",
      borderBottom: "1px solid #eee",
      padding: "0 32px",
      position: "sticky",
      top: 0,
      zIndex: 100,
      fontWeight: 500
    }}>
      <div style={{
        maxWidth: 1200,
        margin: "0 auto",
        display: "flex",
        alignItems: "center",
        height: 64,
        gap: 32
      }}>
        <Link href="/" style={{ fontWeight: 800, fontSize: 24, color: "#2575fc", textDecoration: "none", marginRight: 32 }}>
          Thrivex Studio
        </Link>
        <Link href="/" style={{ marginRight: 24, color: "#fff" }}>Home</Link>
        <div className={styles.dropdownParent} style={{ position: "relative", marginRight: 24 }}>
          <span style={{ color: "#fff" }}>Services ▾</span>
          <div className={styles.dropdownMenu}>
            <div style={{ padding: 12, borderBottom: "1px solid #f0f0f0" }}>
              <Link href="/services/podcast" style={{ color: "#2575fc", fontWeight: 700, textDecoration: 'underline', display: 'block', marginBottom: 4 }}>
                Podcast Production
              </Link>
              <div style={{ fontSize: 14, color: "#222" }}>Fast podcast editing</div>
              <div style={{ fontSize: 14, color: "#222" }}>Podcast setup & strategy</div>
              <div style={{ fontSize: 14, color: "#222" }}>Hosting & distribution</div>
            </div>
            <div style={{ padding: 12, borderBottom: "1px solid #f0f0f0" }}>
              <Link href="/services/web-development" style={{ color: "#2575fc", fontWeight: 700, textDecoration: 'underline', display: 'block', marginBottom: 4 }}>
                Web Development
              </Link>
              <div style={{ fontSize: 14, color: "#222" }}>Website design</div>
              <div style={{ fontSize: 14, color: "#222" }}>Front-end/back-end dev</div>
              <div style={{ fontSize: 14, color: "#222" }}>E-commerce solutions</div>
            </div>
            <div style={{ padding: 12 }}>
              <Link href="/services/video-editing" style={{ color: "#2575fc", fontWeight: 700, textDecoration: 'underline', display: 'block', marginBottom: 4 }}>
                Video Editing
              </Link>
              <div style={{ fontSize: 14, color: "#222" }}>Studio rental</div>
              <div style={{ fontSize: 14, color: "#222" }}>On-site recording</div>
              <div style={{ fontSize: 14, color: "#222" }}>Editing & post-production</div>
            </div>
          </div>
        </div>
        {/* <Link href="/portfolio" style={{ marginRight: 24, color: "#fff" }}>Portfolio / Work</Link> */}
        <Link href="/about-us" style={{ marginRight: 24, color: "#fff" }}>About Us</Link>
        <Link href="/blog" style={{ marginRight: 24, color: "#fff" }}>Blog / Resources</Link>
        <Link href="/pricing" style={{ marginRight: 24, color: "#fff" }}>Pricing / Packages</Link>
        <Link href="/contact" style={{ marginRight: 24, color: "#fff" }}>Contact</Link>
        <div style={{ flex: 1 }} />
        <a href="#cta" style={{
          background: "#2575fc",
          color: "#fff",
          padding: "10px 28px",
          borderRadius: 24,
          fontWeight: 700,
          fontSize: 16,
          textDecoration: "none"
        }}>
          Start Your Project
        </a>
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Menu />
        {children}
      </body>
    </html>
  );
}
